server:
  port: 8080

spring:
  application:
    name: api-gateway
  ## Desde aquí se define el gateway
  cloud:
    gateway:
      routes:
        - id: msboletas #Nombre del ms para el gateway. Identico al declarado en el application.properties del ms
          uri: lb://MSBOLETAS #Ruta del ms
          predicates:
            - Path=/api/v1/boletas/** #La ruta de un controlador del ms
        - id: mspagos
          uri: lb://MSPAGOS
          predicates:
            -  Path=/api/v1/pagos/**       
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka