CREATE SCHEMA IF NOT EXISTS bd_boletas;

CREATE TABLE IF NOT EXISTS bd_boletas.boleta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folio VARCHAR(100) NOT NULL,
    rut_proveedor VARCHAR(20) NOT NULL,
    glosa VARCHAR(255),
    tipo VARCHAR(50) NOT NULL,
    fecha_emision DATE NOT NULL,
    monto_bruto INTEGER NOT NULL,
    monto_neto INTEGER NOT NULL,
    estado VARCHAR(50) NOT NULL
);