CREATE SCHEMA IF NOT EXISTS bd_pagos;

CREATE TABLE IF NOT EXISTS bd_pagos.medio_pago (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(50) NOT NULL,
    estado VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS bd_pagos.cuenta_presupuestaria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    saldo_disponible BIGINT NOT NULL,
    estado VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS bd_pagos.pago (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_pago DATE NOT NULL,
    monto_pagado INT NOT NULL,
    estado VARCHAR(20) NOT NULL,
    folio_boleta VARCHAR(50) NOT NULL,
    rut_proveedor VARCHAR(12) NOT NULL,
    descripcion VARCHAR(100),
    id_medio_pago BIGINT NOT NULL,
    id_cuenta_presupuestaria BIGINT NOT NULL,
    CONSTRAINT fk_medio_pago FOREIGN KEY (id_medio_pago) REFERENCES bd_pagos.medio_pago(id),
    CONSTRAINT fk_cuenta_presupuestaria FOREIGN KEY (id_cuenta_presupuestaria) REFERENCES bd_pagos.cuenta_presupuestaria(id)
);

INSERT INTO bd_pagos.medio_pago (descripcion, estado) VALUES ('Transferencia bancaria', 'Activo');
INSERT INTO bd_pagos.medio_pago (descripcion, estado) VALUES ('Vale vista', 'Activo');
INSERT INTO bd_pagos.medio_pago (descripcion, estado) VALUES ('Cheque', 'Activo');

INSERT INTO bd_pagos.cuenta_presupuestaria (codigo, nombre, saldo_disponible, estado) VALUES ('CP-001', 'Servicios tecnológicos', 1000000, 'Activo');
INSERT INTO bd_pagos.cuenta_presupuestaria (codigo, nombre, saldo_disponible, estado) VALUES ('CP-002', 'Artículos de oficina', 500000, 'Activo');
INSERT INTO bd_pagos.cuenta_presupuestaria (codigo, nombre, saldo_disponible, estado) VALUES ('CP-003', 'Gastos de viaje', 200000, 'Activo');